const mainHandler=async(req:Request)=>{try{
 const url=new URL(req.url),action=url.searchParams.get("action");
 if(!action&&req.method==="GET")return await servePage(req);
 if(req.method==="POST"){
  const origin=req.headers.get("origin"),trusted=req.headers.get("x-noria-origin")||new URL(req.url).origin;
  if(!origin||origin!==trusted)return json({error:"Origine de la requête refusée."},403);
 }
 if(action==="login"&&req.method==="POST"){
  const b=await readBody(req),identifier=String(b.identifier||"").trim().toUpperCase(),password=String(b.password||"");
  if(!identifier||!password)return json({error:"Saisissez votre identifiant et votre mot de passe."},400);
  const ip=req.headers.get("x-forwarded-for")?.split(",")[0]||"unknown",rateKey=await hmac(`${ip}:${identifier}`),attemptResult=await db("rpc/noria_login_attempt","POST",{p_key_hash:rateKey}),attempts=Number(attemptResult.data||0),now=Date.now();
  if(attempts>8)return json({error:"Trop de tentatives. Réessayez dans quelques minutes."},429);
  const {data}=await db(qp("hr_accounts",{select:"employee_id,identifier,password_hash,role,enabled,must_change_password,session_version",identifier:`eq.${identifier}`,limit:"1"})),a=data?.[0];
  if(!a?.enabled||!await verifyPassword(password,a.password_hash))return json({error:"Identifiant ou mot de passe incorrect."},401);
  await db(qp("noria_login_attempts",{attempt_key_hash:`eq.${rateKey}`}),"DELETE");
  const {data:p}=await db(qp("employees",{select:"first_name,last_name,role",id:`eq.${a.employee_id}`,limit:"1"})),age=b.remember?2592000:28800,token=await makeToken({sub:a.employee_id,ver:Number(a.session_version||1),iat:Math.floor(now/1000),exp:Math.floor(now/1000)+age});
  await db(qp("hr_accounts",{employee_id:`eq.${a.employee_id}`}),"PATCH",{last_login_at:new Date().toISOString()});
  return json({user:{identifier:a.identifier,role:a.role,must_change_password:a.must_change_password===true,...p?.[0]}},200,{"Set-Cookie":cookieHeader(token,age)});
 }
 if(action==="logout"&&req.method==="POST")return json({ok:true},200,{"Set-Cookie":cookieHeader("",0)});
 const user=await current(req);
 if(!user)return json({error:"Votre session a expiré. Reconnectez-vous."},401,{"Set-Cookie":cookieHeader("",0)});
 if(user.must_change_password&&!(["me","dashboard","change-password","notifications","notification-read","logout"].includes(action||"")))return json({error:"Changez votre mot de passe provisoire avant de continuer."},403);
 if(action==="me"&&req.method==="GET"){
  const {data}=await db(qp("employees",{select:"first_name,last_name,role",id:`eq.${user.employee_id}`,limit:"1"}));
  return json({user:{...user,...data?.[0]}});
 }
 if(action==="dashboard"&&req.method==="GET"){const dash=await getDashboard(user),org=(await db("noria_settings?select=setting_value&setting_key=eq.organization&limit=1")).data?.[0]?.setting_value;return json({...dash,organization:org?.name||"Chromatotec"})}
 if(action==="change-password"&&req.method==="POST"){
  const b=await readBody(req);if(typeof b.new_password!=="string"||b.new_password.length<12)return json({error:"Le nouveau mot de passe doit contenir au moins 12 caractères."},400);
  const {data}=await db(qp("hr_accounts",{select:"password_hash,session_version",employee_id:`eq.${user.employee_id}`,limit:"1"})),a=data?.[0];
  if(!a)return json({error:"Compte indisponible."},404);
  if(!user.must_change_password&&!await verifyPassword(String(b.current_password||""),a.password_hash))return json({error:"Mot de passe actuel incorrect."},401);
  const version=Number(a.session_version||1)+1;await db(qp("hr_accounts",{employee_id:`eq.${user.employee_id}`}),"PATCH",{password_hash:await hashPassword(b.new_password),must_change_password:false,session_version:version});
  const token=await makeToken({sub:user.employee_id,ver:version,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+28800});await audit(user,"password_changed","account",user.employee_id);
  return json({ok:true},200,{"Set-Cookie":cookieHeader(token,28800)});
 }
 if(action==="employees"&&req.method==="GET"){
  const ids=await visibleIDs(user),filter=ids===null?{}:{id:`in.(${ids.join(",")})`},rows=await db(qp("employees",{select:employeeFields,order:"last_name.asc",limit:"500",...filter}));return json({employees:rows.data||[]});
 }
 if(action==="add-employee"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Seule l’administration RH peut créer un dossier."},403);
  const b=await readBody(req);for(const f of ["identifier","password","first_name","last_name","staff_number"])if(typeof b[f]!=="string"||b[f].trim().length<2)return json({error:`Le champ ${f} est requis.`},400);
  if(b.password.length<12)return json({error:"Le mot de passe temporaire doit contenir au moins 12 caractères."},400);
  const identifier=b.identifier.trim().toUpperCase(),role=["employee","manager"].includes(b.role)?b.role:"employee",managerId=String(b.manager_id||"")||null;
  if(managerId&&!await inScope(user,managerId))return json({error:"Manager de rattachement invalide."},400);
  const initialBalance=Number(b.leave_balance||0),workPercentage=Number(b.work_percentage||100);if(!Number.isFinite(initialBalance)||initialBalance<0||!Number.isFinite(workPercentage)||workPercentage<=0||workPercentage>100)return json({error:"Solde initial ou taux d’activité invalide."},400);const created=await db("employees","POST",{staff_number:b.staff_number.trim(),first_name:b.first_name.trim(),last_name:b.last_name.trim(),job_title:String(b.job_title||"").trim()||null,department:String(b.department||"").trim()||null,contract_type:String(b.contract_type||"CDI").trim(),start_date:b.start_date||parisDate(),location:String(b.location||"").trim()||null,phone_number:String(b.phone_number||"").trim()||null,work_percentage:workPercentage,manager_id:managerId,status:b.status==="onboarding"?"onboarding":"active",role,leave_balance:initialBalance}),e=created.data?.[0];
  try{await db("hr_accounts","POST",{employee_id:e.id,identifier,password_hash:await hashPassword(b.password),role,enabled:true,must_change_password:true})}catch(err){await db(qp("employees",{id:`eq.${e.id}`}),"DELETE");throw err}
  if(initialBalance>0)await db("leave_balance_transactions","POST",{employee_id:e.id,leave_type:"Congés payés",delta_days:initialBalance,effective_date:b.start_date||parisDate(),source_type:"opening_balance",source_id:e.id,created_by:user.employee_id,note:"Solde initial du dossier"});await audit(user,"employee_created","employee",e.id,{role});await notify(e.id,"account","Votre accès Noria est prêt","Changez votre mot de passe provisoire lors de votre première connexion.","parametres");
  return json({employee_id:e.id,identifier},201);
 }
 if(action==="employee-update"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Accès réservé à l’administration RH."},403);const b=await readBody(req);if(!b.id)return json({error:"Profil introuvable."},400);const id=String(b.id).replace(/[^\w-]/g,"");
  const before=(await db(qp("employees",{select:employeeFields,id:`eq.${id}`,limit:"1"}))).data?.[0];if(!before)return json({error:"Profil introuvable."},404);
  const update:any={};for(const f of ["first_name","last_name","job_title","department","contract_type","start_date","end_date","location","phone_number","work_percentage","status","manager_id"])if(b[f]!==undefined)update[f]=b[f]===""?null:b[f];
  if(update.work_percentage!==undefined&&(Number(update.work_percentage)<=0||Number(update.work_percentage)>100))return json({error:"Le taux d’activité doit être entre 1 et 100 %."},400);
  const r=await db(qp("employees",{id:`eq.${id}`}),"PATCH",update);
  for(const [field,value]of Object.entries(update))if(String((before as any)[field]??"")!==String(value??""))await db("employee_change_log","POST",{employee_id:id,changed_by:user.employee_id,field_name:field,old_value:String((before as any)[field]??"")||null,new_value:String(value??"")||null,effective_at:b.effective_at||new Date().toISOString(),reason:String(b.reason||"").slice(0,500)||null});
  if(update.status){const {data:account}=await db(qp("hr_accounts",{select:"employee_id,session_version",employee_id:`eq.${id}`,limit:"1"}));if(account?.[0])await db(qp("hr_accounts",{employee_id:`eq.${id}`}),"PATCH",{enabled:update.status!=="inactive",session_version:Number(account[0].session_version||1)+1})}
  await audit(user,"employee_updated","employee",id,{fields:Object.keys(update)});await notify(id,"profile","Votre dossier RH a été mis à jour","Consultez votre espace pour voir les informations modifiées.","equipe",id);return json({ok:!!r.data?.length});
 }
 if(action==="employee-history"&&req.method==="GET"){
  const id=String(url.searchParams.get("id")||"").replace(/[^\w-]/g,"");if(!await inScope(user,id))return json({error:"Dossier indisponible."},403);
  const rows=await namedRows("employee_change_log","id,employee_id,changed_by,field_name,old_value,new_value,effective_at,reason,created_at",{employee_id:`eq.${id}`});return json({history:rows});
 }
 if(action==="profile-change"&&req.method==="POST"){
  const b=await readBody(req),changes:any={};for(const field of ["phone_number","location"])if(b[field]!==undefined)changes[field]=String(b[field]).trim().slice(0,160);if(!Object.keys(changes).length)return json({error:"Aucune modification autorisée n’a été saisie."},400);
  const result=await db("profile_change_requests","POST",{employee_id:user.employee_id,requested_changes:changes,reason:String(b.reason||"").slice(0,500)||null});const admins=await namedRows("hr_accounts","employee_id",{role:"eq.admin",enabled:"eq.true"});for(const a of admins)await notify(a.employee_id,"profile_request","Demande de correction de dossier",`Une demande de correction attend votre examen.`,"parametres",result.data?.[0]?.id);
  await audit(user,"profile_change_requested","employee",user.employee_id,{fields:Object.keys(changes)});return json({ok:true},201);
 }
 if(action==="profile-changes"&&req.method==="GET"){
  let filter:any={status:"eq.pending"};if(user.role==="employee")filter.employee_id=`eq.${user.employee_id}`;else if(user.role==="manager"){const ids=await visibleIDs(user);filter.employee_id=`in.(${ids.join(",")})`}
  const rows=await namedRows("profile_change_requests","id,employee_id,requested_changes,reason,status,created_at",filter),people=await employeesFor(user);return json({requests:rows.map((r:any)=>({...r,...people.find((p:any)=>p.id===r.employee_id)}))});
 }
 if(action==="profile-change-decision"&&req.method==="POST"){
  const b=await readBody(req);if(!["approved","rejected"].includes(b.status))return json({error:"Décision invalide."},400);const {data}=await db(qp("profile_change_requests",{select:"id,employee_id,requested_changes,status",id:`eq.${String(b.id||"").replace(/[^\w-]/g,"")}`,status:"eq.pending",limit:"1"})),item=data?.[0];if(!item||!await inScope(user,item.employee_id)||user.role==="manager"&&item.employee_id===user.employee_id)return json({error:"Demande indisponible."},404);if(user.role==="employee")return json({error:"Action réservée au manager ou à l’administration RH."},403);
  if(b.status==="approved"){const safe:any={};for(const f of ["phone_number","location"])if(item.requested_changes?.[f]!==undefined)safe[f]=item.requested_changes[f];const old=(await db(qp("employees",{select:"phone_number,location",id:`eq.${item.employee_id}`,limit:"1"}))).data?.[0]||{};await db(qp("employees",{id:`eq.${item.employee_id}`}),"PATCH",safe);for(const [field,value]of Object.entries(safe))await db("employee_change_log","POST",{employee_id:item.employee_id,changed_by:user.employee_id,field_name:field,old_value:(old as any)[field]||null,new_value:String(value||"")||null,reason:"Demande de correction approuvée"})}
  await db(qp("profile_change_requests",{id:`eq.${item.id}`}),"PATCH",{status:b.status,reviewed_by:user.employee_id,reviewed_at:new Date().toISOString()});await notify(item.employee_id,"profile_request",b.status==="approved"?"Votre correction a été appliquée":"Votre demande a été refusée",String(b.reason||"Consultez l’équipe RH pour plus de détails."),"parametres",item.id);await audit(user,"profile_change_decided","profile_change_request",item.id,{status:b.status});return json({ok:true});
 }
 if(action==="leave"&&req.method==="POST"){
  const b=await readBody(req),start=String(b.start_date||""),end=String(b.end_date||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/\d{4}-\d{2}-\d{2}$/.test(end)||start>end)return json({error:"Choisissez une période valide."},400);
  const leaveType=String(b.leave_type||"Congés payés").slice(0,80),policies=await namedRows("leave_policies","leave_type,counts_weekends,paid,requires_approval,enabled",{leave_type:`eq.${leaveType}`,enabled:"eq.true"});if(policies.length===0&&leaveType!=="Congés payés")return json({error:"Ce type d’absence n’est pas encore activé par les RH."},400);
  const person=(await db(qp("employees",{select:"location,leave_balance",id:`eq.${user.employee_id}`,limit:"1"}))).data?.[0],holidays=(await db(qp("organization_holidays",{select:"holiday_date,location",holiday_date:`gte.${start}`,and:`(holiday_date.lte.${end})`,limit:"1000"}))).data||[],holidaySet=new Set(holidays.filter((h:any)=>!h.location||h.location===person?.location).map((h:any)=>h.holiday_date)),days=workdays(start,end,holidaySet,policies[0]?.counts_weekends===true);
  if(days<1||days>60)return json({error:"La période doit représenter entre 1 et 60 jours selon les règles configurées."},400);const overlap=await db(qp("leave_requests",{select:"id",employee_id:`eq.${user.employee_id}`,status:"in.(pending,approved)",start_date:`lte.${end}`,end_date:`gte.${start}`,limit:"1"}));if(overlap.data?.length)return json({error:"Une demande existe déjà sur cette période."},409);
  const row=await db("leave_requests","POST",{employee_id:user.employee_id,leave_type:start?leaveType:leaveType,start_date:start,end_date:end,days,status:"pending",note:String(b.note||"").slice(0,1000)||null}),id=row.data?.[0]?.id;
  const {data:employee}=await db(qp("employees",{select:"manager_id",id:`eq.${user.employee_id}`,limit:"1"}));const recipients=new Set<string>();if(employee?.[0]?.manager_id)recipients.add(employee[0].manager_id);for(const a of await namedRows("hr_accounts","employee_id",{role:"eq.admin",enabled:"eq.true"}))recipients.add(a.employee_id);for(const to of recipients)await notify(to,"leave","Nouvelle demande d’absence",`${days} jour(s) à examiner.`,"conges",id);await audit(user,"leave_requested","leave_request",id,{leave_type:leaveType,days});return json({ok:true,days},201);
 }
 if(action==="leave-status"&&req.method==="POST"){
  const b=await readBody(req);if(!["approved","rejected"].includes(b.status))return json({error:"Décision invalide."},400);const {data}=await db(qp("leave_requests",{select:"id,employee_id,status,days,leave_type,start_date,end_date",id:`eq.${String(b.id||"").replace(/[^\w-]/g,"")}`,status:"eq.pending",limit:"1"})),leave=data?.[0];if(!leave||!await inScope(user,leave.employee_id)||user.role==="employee"||user.role==="manager"&&leave.employee_id===user.employee_id)return json({error:"Demande indisponible."},404);
  const updated=await db(qp("leave_requests",{id:`eq.${leave.id}`,status:"eq.pending"}),"PATCH",{status:b.status,reviewed_by:user.employee_id,reviewed_at:new Date().toISOString()});if(!updated.data?.length)return json({error:"Cette demande a déjà été traitée."},409);
  const policy=(await db(qp("leave_policies",{select:"paid",leave_type:`eq.${leave.leave_type}`,limit:"1"}))).data?.[0],deduct=policy?policy.paid:leave.leave_type==="Congés payés";
  if(b.status==="approved"&&deduct){const person=(await db(qp("employees",{select:"leave_balance",id:`eq.${leave.employee_id}`,limit:"1"}))).data?.[0],balance=Number(person?.leave_balance||0);if(balance<Number(leave.days)){await db(qp("leave_requests",{id:`eq.${leave.id}`}),"PATCH",{status:"pending",reviewed_by:null,reviewed_at:null});return json({error:"Le solde de congés est insuffisant."},409)}await db(qp("employees",{id:`eq.${leave.employee_id}`}),"PATCH",{leave_balance:balance-Number(leave.days)});await db("leave_balance_transactions","POST",{employee_id:leave.employee_id,leave_type:leave.leave_type,delta_days:-Number(leave.days),effective_date:leave.start_date,source_type:"leave_request",source_id:leave.id,created_by:user.employee_id,note:"Demande approuvée"})}
  await notify(leave.employee_id,"leave",b.status==="approved"?"Votre demande a été validée":"Votre demande a été refusée",String(b.reason||"Consultez votre espace RH pour le détail."),"conges",leave.id);await audit(user,"leave_decided","leave_request",leave.id,{status:b.status});return json({ok:true});
 }
 if(action==="leave-cancel"&&req.method==="POST"){
  const b=await readBody(req),id=String(b.id||"").replace(/[^\w-]/g,"");const r=await db(qp("leave_requests",{id:`eq.${id}`,employee_id:`eq.${user.employee_id}`,status:"eq.pending"}),"PATCH",{status:"cancelled"});if(!r.data?.length)return json({error:"Seules vos demandes en attente peuvent être annulées."},409);await audit(user,"leave_cancelled","leave_request",id);return json({ok:true});
 }
 if(action==="attendance"&&req.method==="GET"){
  const ids=await visibleIDs(user),filters=idFilter(ids),records=await namedRows("attendance_records","id,employee_id,work_date,clock_in,clock_out,work_minutes,breaks,note,created_at",filters),people=await employeesFor(user);return json({records:records.map((r:any)=>({...r,...people.find((p:any)=>p.id===r.employee_id)}))});
 }
 if(action==="attendance-punch"&&req.method==="POST"){
  const b=await readBody(req),day=parisDate(),found=await namedRows("attendance_records","id,clock_in,clock_out,work_date,breaks",{employee_id:`eq.${user.employee_id}`,work_date:`eq.${day}`});const closed=(await db(`attendance_period_closures?select=id&status=eq.closed&period_month=eq.${day.slice(0,7)}-01&limit=1`)).data?.length;if(closed)return json({error:"Cette période est clôturée par les RH."},409);if(b.event==="in"){if(found[0]?.clock_in)return json({error:"Votre journée a déjà commencé."},409);if(found[0])return json({error:"Pointage déjà clôturé pour aujourd’hui."},409);const r=await db("attendance_records","POST",{employee_id:user.employee_id,work_date:day,clock_in:new Date().toISOString(),breaks:[]});await audit(user,"attendance_clock_in","attendance",r.data?.[0]?.id)}else{const row=found[0];if(!row?.clock_in||row.clock_out)return json({error:"Aucun pointage en cours à clôturer."},409);const now=new Date().toISOString(),breaks=Array.isArray(row.breaks)?row.breaks:[];if(b.event==="break-start"){if(breaks.some((x:any)=>x.start&&!x.end))return json({error:"Une pause est déjà en cours."},409);breaks.push({start:now,end:null});await db(qp("attendance_records",{id:`eq.${row.id}`}),"PATCH",{breaks});await audit(user,"attendance_break_started","attendance",row.id)}else if(b.event==="break-end"){const current=[...breaks].reverse().find((x:any)=>x.start&&!x.end);if(!current)return json({error:"Aucune pause n’est en cours."},409);current.end=now;await db(qp("attendance_records",{id:`eq.${row.id}`}),"PATCH",{breaks});await audit(user,"attendance_break_ended","attendance",row.id)}else if(b.event==="out"){if(breaks.some((x:any)=>x.start&&!x.end))return json({error:"Terminez votre pause avant de clôturer la journée."},409);const gross=Math.floor((Date.now()-new Date(row.clock_in).getTime())/60000),breakMinutes=breaks.reduce((n:number,x:any)=>n+(x.end?Math.max(0,Math.floor((new Date(x.end).getTime()-new Date(x.start).getTime())/60000)):0),0);await db(qp("attendance_records",{id:`eq.${row.id}`}),"PATCH",{clock_out:now,work_minutes:Math.max(0,gross-breakMinutes)});await audit(user,"attendance_clock_out","attendance",row.id)}else return json({error:"Action de pointage invalide."},400)}return json({ok:true});
 }
 if(action==="attendance-correction"&&req.method==="POST"){
  const b=await readBody(req),id=String(b.attendance_id||"").replace(/[^\w-]/g,"");const record=(await db(qp("attendance_records",{select:"id,employee_id,clock_in,clock_out",id:`eq.${id}`,limit:"1"}))).data?.[0];if(!record||record.employee_id!==user.employee_id)return json({error:"Pointage indisponible."},404);if(!b.reason||String(b.reason).trim().length<4)return json({error:"Expliquez brièvement la correction demandée."},400);
  const row=await db("attendance_change_requests","POST",{attendance_id:id,employee_id:user.employee_id,requested_clock_in:b.clock_in||record.clock_in,requested_clock_out:b.clock_out||record.clock_out,original_clock_in:record.clock_in,original_clock_out:record.clock_out,reason:String(b.reason).trim().slice(0,500)});const {data:person}=await db(qp("employees",{select:"manager_id",id:`eq.${user.employee_id}`,limit:"1"}));const recipients=new Set<string>();if(person?.[0]?.manager_id)recipients.add(person[0].manager_id);for(const a of await namedRows("hr_accounts","employee_id",{role:"eq.admin",enabled:"eq.true"}))recipients.add(a.employee_id);for(const to of recipients)await notify(to,"attendance","Correction de pointage à examiner","Un collaborateur a demandé une correction.","temps",row.data?.[0]?.id);await audit(user,"attendance_correction_requested","attendance",id);return json({ok:true},201);
 }
 if(action==="attendance-corrections"&&req.method==="GET"){
  let filter:any={};if(user.role==="employee")filter.employee_id=`eq.${user.employee_id}`;else if(user.role==="manager"){const ids=await visibleIDs(user);filter.employee_id=`in.(${ids.join(",")})`};const rows=await namedRows("attendance_change_requests","id,attendance_id,employee_id,requested_clock_in,requested_clock_out,reason,status,reviewed_by,reviewed_at,created_at",filter),people=await employeesFor(user);return json({requests:rows.map((r:any)=>({...r,...people.find((p:any)=>p.id===r.employee_id)}))});
 }
 if(action==="attendance-correction-decision"&&req.method==="POST"){
  const b=await readBody(req);if(!["approved","rejected"].includes(b.status)||user.role==="employee")return json({error:"Décision invalide."},403);const request=(await db(qp("attendance_change_requests",{select:"id,attendance_id,employee_id,requested_clock_in,requested_clock_out,status",id:`eq.${String(b.id||"").replace(/[^\w-]/g,"")}`,status:"eq.pending",limit:"1"}))).data?.[0];if(!request||!await inScope(user,request.employee_id)||user.role==="manager"&&request.employee_id===user.employee_id)return json({error:"Demande indisponible."},404);
  if(b.status==="approved"){const month=String((await db(qp("attendance_records",{select:"work_date",id:`eq.${request.attendance_id}`,limit:"1"}))).data?.[0]?.work_date||"").slice(0,7),closed=(await db(`attendance_period_closures?select=id&status=eq.closed&period_month=eq.${month}-01&limit=1`)).data?.length;if(closed)return json({error:"La période est clôturée. Faites-la rouvrir par les RH avant cette correction."},409);const input=new Date(request.requested_clock_in),output=new Date(request.requested_clock_out);if(!Number.isFinite(input.getTime())||!Number.isFinite(output.getTime())||output<input)return json({error:"Les horaires demandés sont invalides."},409);await db(qp("attendance_records",{id:`eq.${request.attendance_id}`}),"PATCH",{clock_in:input.toISOString(),clock_out:output.toISOString(),work_minutes:Math.floor((output.getTime()-input.getTime())/60000),note:String(b.note||request.reason).slice(0,500)})}
  await db(qp("attendance_change_requests",{id:`eq.${request.id}`}),"PATCH",{status:b.status,reviewed_by:user.employee_id,reviewed_at:new Date().toISOString()});if(b.status==="approved")await db(qp("attendance_records",{id:`eq.${request.attendance_id}`}),"PATCH",{approved_by:user.employee_id,approved_at:new Date().toISOString()});await notify(request.employee_id,"attendance",b.status==="approved"?"Correction de pointage validée":"Correction de pointage refusée",String(b.reason||"Consultez votre manager ou les RH."),"temps",request.attendance_id);await audit(user,"attendance_correction_decided","attendance",request.attendance_id,{status:b.status});return json({ok:true});
 }
 if(action==="attendance-period"&&req.method==="GET"){
  if(!isHR(user))return json({error:"Accès réservé aux RH."},403);const month=String(url.searchParams.get("month")||parisDate().slice(0,7));if(!/^\d{4}-\d{2}$/.test(month))return json({error:"Mois invalide."},400);const row=(await db(`attendance_period_closures?select=id,period_month,status,closed_by,closed_at,note&period_month=eq.${month}-01&limit=1`)).data?.[0]||null;return json({period:row});
 }
 if(action==="attendance-period-close"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Clôture réservée aux RH."},403);const b=await readBody(req),month=String(b.month||"");if(!/^\d{4}-\d{2}$/.test(month))return json({error:"Mois invalide."},400);const status=b.status==="reopened"?"reopened":"closed",existing=(await db(`attendance_period_closures?select=id&period_month=eq.${month}-01&limit=1`)).data?.[0];const value={period_month:`${month}-01`,status,closed_by:user.employee_id,closed_at:new Date().toISOString(),note:String(b.note||"").slice(0,500)||null};const r=existing?await db(`attendance_period_closures?id=eq.${existing.id}`,"PATCH",value):await db("attendance_period_closures","POST",value);await audit(user,status==="closed"?"attendance_period_closed":"attendance_period_reopened","attendance_period",r.data?.[0]?.id,{month});return json({ok:true,period:r.data?.[0]});
 }
 if(action==="recruitment"&&req.method==="GET"){
  if(user.role==="employee")return json({error:"Accès réservé à l’équipe RH et aux managers concernés."},403);const jobFilter=user.role==="manager"?{hiring_manager_id:`eq.${user.employee_id}`}:{},jobs=await namedRows("job_postings","id,title,department,location,contract_type,status,description,opened_at,created_at,hiring_manager_id",jobFilter),jobIds=jobs.map((j:any)=>j.id);const candidates=jobIds.length?await namedRows("candidates","id,job_posting_id,first_name,last_name,stage,source,applied_at,notes,privacy_notice_at,retention_until,created_at",user.role==="manager"?{job_posting_id:`in.(${jobIds.join(",")})`}:{}):[];return json({jobs,candidates:candidates.map((c:any)=>({...c,job_title:jobs.find((j:any)=>j.id===c.job_posting_id)?.title||"Candidature spontanée"}))});
 }
 if(action==="job-save"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Création de poste réservée aux RH."},403);const b=await readBody(req);if(String(b.title||"").trim().length<3)return json({error:"Le titre du poste est requis."},400);const r=await db("job_postings","POST",{title:String(b.title).trim(),department:String(b.department||"").trim()||null,location:String(b.location||"").trim()||null,contract_type:String(b.contract_type||"").trim()||null,status:"open",description:String(b.description||"").slice(0,10000)||null,hiring_manager_id:b.hiring_manager_id||null,opened_at:b.opened_at||parisDate()});await audit(user,"job_created","job_posting",r.data?.[0]?.id);return json({job:r.data?.[0]},201);
 }
 if(action==="job-close"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Action réservée aux RH."},403);const b=await readBody(req),id=String(b.id||"").replace(/[^\w-]/g,"");await db(qp("job_postings",{id:`eq.${id}`}),"PATCH",{status:"closed"});await audit(user,"job_closed","job_posting",id);return json({ok:true});
 }
 if(action==="candidate-save"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Création de candidature réservée aux RH."},403);const b=await readBody(req);if(!String(b.first_name||"").trim()||!String(b.last_name||"").trim())return json({error:"Le nom du candidat est requis."},400);if(b.privacy_notice_confirmed!==true&&b.privacy_notice_confirmed!=="on")return json({error:"Confirmez que l’information relative aux données candidates a été remise."},400);const job=String(b.job_posting_id||"").trim(),retention=(await db("noria_settings?select=setting_value&setting_key=eq.retention&limit=1")).data?.[0]?.setting_value,retentionDays=Number(retention?.candidate_days||0),retentionDate=b.retention_until||(retentionDays>0?dateAfter(b.applied_at||parisDate(),retentionDays):null),r=await db("candidates","POST",{first_name:String(b.first_name).trim().slice(0,100),last_name:String(b.last_name).trim().slice(0,100),job_posting_id:job||null,source:String(b.source||"").trim().slice(0,160)||null,applied_at:b.applied_at||parisDate(),notes:String(b.notes||"").slice(0,5000)||null,privacy_notice_at:new Date().toISOString(),retention_until:retentionDate});await audit(user,"candidate_created","candidate",r.data?.[0]?.id);return json({candidate:r.data?.[0]},201);
 }
 if(action==="candidate-stage"&&req.method==="POST"){
  if(user.role==="employee")return json({error:"Action réservée aux RH et managers concernés."},403);const b=await readBody(req);if(!["applied","screening","interview","offer","hired","declined"].includes(b.stage))return json({error:"Étape invalide."},400);const id=String(b.id||"").replace(/[^\w-]/g,""),candidate=(await db(qp("candidates",{select:"id,job_posting_id",id:`eq.${id}`,limit:"1"}))).data?.[0];if(!candidate)return json({error:"Candidature indisponible."},404);if(user.role==="manager"){const job=(await db(qp("job_postings",{select:"id",id:`eq.${candidate.job_posting_id}`,hiring_manager_id:`eq.${user.employee_id}`,limit:"1"}))).data?.[0];if(!job)return json({error:"Candidature hors de votre périmètre."},403)}await db(qp("candidates",{id:`eq.${id}`}),"PATCH",{stage:b.stage});await audit(user,"candidate_stage_changed","candidate",id,{stage:b.stage});return json({ok:true});
 }
 if(action==="training"&&req.method==="GET"){
  const ids=await visibleIDs(user),enrollFilter=ids===null?{}:{employee_id:`in.(${ids.join(",")})`},[courses,enrollments]=await Promise.all([namedRows("training_courses","id,title,provider,description,starts_at,ends_at,seats,status,created_at",user.role==="employee"?{status:"in.(open,planned,in_progress,completed)"}:{}),namedRows("training_enrollments","id,training_id,employee_id,status,completed_at,completion_note",enrollFilter)]);const people=await employeesFor(user);return json({courses,enrollments:enrollments.map((e:any)=>({...e,title:courses.find((c:any)=>c.id===e.training_id)?.title||"Formation",...people.find((person:any)=>person.id===e.employee_id)}))});
 }
 if(action==="training-save"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Création réservée aux RH."},403);const b=await readBody(req);if(String(b.title||"").trim().length<3)return json({error:"Le nom de la formation est requis."},400);const r=await db("training_courses","POST",{title:String(b.title).trim(),provider:String(b.provider||"").trim()||null,description:String(b.description||"").slice(0,5000)||null,starts_at:b.starts_at||null,ends_at:b.ends_at||null,seats:b.seats?Number(b.seats):null,status:"open"});await audit(user,"training_created","training_course",r.data?.[0]?.id);return json({course:r.data?.[0]},201);
 }
 if(action==="training-enroll"&&req.method==="POST"){
  const b=await readBody(req),id=String(b.training_id||"").replace(/[^\w-]/g,""),course=(await db(qp("training_courses",{select:"id,status,seats",id:`eq.${id}`,limit:"1"}))).data?.[0];if(!course||course.status!=="open")return json({error:"Les inscriptions sont fermées."},409);const exists=await db(qp("training_enrollments",{select:"id",training_id:`eq.${id}`,employee_id:`eq.${user.employee_id}`,limit:"1"}));if(exists.data?.length)return json({error:"Vous êtes déjà inscrit·e."},409);let status="registered";if(course.seats!==null){const enrollments=await db(qp("training_enrollments",{select:"id",training_id:`eq.${id}`,status:"in.(registered,completed)",limit:"1000"}));if((enrollments.data?.length||0)>=Number(course.seats))status="waitlisted"}await db("training_enrollments","POST",{training_id:id,employee_id:user.employee_id,status});await audit(user,status==="waitlisted"?"training_waitlisted":"training_enrolled","training_course",id);return json({ok:true,status},201);
 }
 if(action==="training-completion"&&req.method==="POST"){
  const b=await readBody(req),id=String(b.id||"").replace(/[^\w-]/g,""),row=(await db(qp("training_enrollments",{select:"id,employee_id,training_id,status",id:`eq.${id}`,limit:"1"}))).data?.[0];if(user.role==="employee"||!row||!await inScope(user,row.employee_id))return json({error:"Inscription indisponible."},404);const status=b.status==="cancelled"?"cancelled":"completed";await db(qp("training_enrollments",{id:`eq.${id}`}),"PATCH",{status,completed_at:status==="completed"?new Date().toISOString():null,completion_note:String(b.note||"").slice(0,500)||null});if(status==="cancelled"){const course=(await db(qp("training_courses",{select:"seats",id:`eq.${row.training_id}`,limit:"1"}))).data?.[0];if(course?.seats!==null){const waiting=(await db(qp("training_enrollments",{select:"id,employee_id",training_id:`eq.${row.training_id}`,status:"eq.waitlisted",order:"created_at.asc",limit:"1"}))).data?.[0];if(waiting){await db(qp("training_enrollments",{id:`eq.${waiting.id}`}),"PATCH",{status:"registered"});await notify(waiting.employee_id,"training","Une place s’est libérée", "Votre inscription est confirmée.","talents",row.training_id)}}}await notify(row.employee_id,"training","Formation mise à jour",status==="completed"?"Votre participation a été marquée comme terminée.":"Votre inscription a été annulée.","talents");await audit(user,"training_completion_updated","training_enrollment",id,{status});return json({ok:true});
 }
 if(action==="documents"&&req.method==="GET"){
  const ids=await visibleIDs(user),filter=ids===null?{}:{employee_id:`in.(${ids.join(",")})`},rows=await namedRows("employee_documents","id,employee_id,title,document_type,storage_path,visibility,uploaded_at,retention_until,version",filter),people=await employeesFor(user),docs=await Promise.all(rows.filter((d:any)=>user.role==="admin"||user.role==="employee"&&d.employee_id===user.employee_id&&d.visibility==="private").map(async(d:any)=>({...d,...people.find((p:any)=>p.id===d.employee_id),...(await signedDoc(d.storage_path))})));return json({documents:docs});
 }
 if(action==="document-upload"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Dépôt réservé à l’administration RH."},403);const b=await readBody(req),employeeId=String(b.employee_id||"");if(!await inScope(user,employeeId))return json({error:"Ce dossier n’est pas dans votre périmètre."},403);if(!b.content_base64||String(b.content_base64).length>7000000)return json({error:"Fichier absent ou trop volumineux (5 Mo maximum)."},400);
  const name=String(b.file_name||"document").replace(/[^\p{L}\p{N}._-]/gu,"_").slice(0,120),path=`${employeeId}/${crypto.randomUUID()}-${name}`,bytes=Uint8Array.from(atob(b.content_base64),c=>c.charCodeAt(0)),mime=String(b.content_type||"application/octet-stream");if(!["application/pdf","image/png","image/jpeg"].includes(mime))return json({error:"Pour garantir un dépôt sûr, seuls les fichiers PDF, PNG et JPEG sont acceptés pour le moment."},400);if(mime==="application/pdf"&&new TextDecoder().decode(bytes.slice(0,4))!=="%PDF"||mime==="image/png"&&Array.from(bytes.slice(0,4)).join(",")!=="137,80,78,71"||mime==="image/jpeg"&&Array.from(bytes.slice(0,3)).join(",")!=="255,216,255")return json({error:"Le contenu ne correspond pas au format annoncé."},400);
  try{await storage("bucket","POST",JSON.stringify({id:"noria-documents",name:"noria-documents",public:false,file_size_limit:5242880,allowed_mime_types:["application/pdf","image/png","image/jpeg"]}),{"Content-Type":"application/json"})}catch(err){if(!String((err as any)?.message||"").toLowerCase().includes("already"))throw err}
  await storage(`object/noria-documents/${path.split("/").map(encodeURIComponent).join("/")}`,"POST",bytes,{"Content-Type":mime,"x-upsert":"false"});const retention=(await db("noria_settings?select=setting_value&setting_key=eq.retention&limit=1")).data?.[0]?.setting_value,retentionDays=Number(retention?.document_days||0),retentionDate=b.retention_until||(retentionDays>0?dateAfter(parisDate(),retentionDays):null);try{const r=await db("employee_documents","POST",{employee_id:employeeId,title:String(b.title||name).slice(0,160),document_type:String(b.document_type||"other").slice(0,80),storage_path:path,visibility:"private",created_by:user.employee_id,retention_until:retentionDate});await audit(user,"document_uploaded","employee_document",r.data?.[0]?.id,{document_type:String(b.document_type||"other")})}catch(err){await storage(`object/noria-documents/${path.split("/").map(encodeURIComponent).join("/")}`,"DELETE");throw err}return json({ok:true},201);
 }
 if(action==="reviews"&&req.method==="GET"){
  const ids=await visibleIDs(user),filter=ids===null?{}:{employee_id:`in.(${ids.join(",")})`},rows=await namedRows("performance_reviews","id,employee_id,reviewer_id,review_type,scheduled_at,status,summary,goals,validated_at,created_at",filter),people=await employeesFor(user);return json({reviews:rows.map((r:any)=>({...r,...people.find((p:any)=>p.id===r.employee_id)}))});
 }
 if(action==="review-save"&&req.method==="POST"){
  const b=await readBody(req);if(user.role==="employee"||!await inScope(user,String(b.employee_id||"")))return json({error:"Planification hors de votre périmètre."},403);const r=await db("performance_reviews","POST",{employee_id:b.employee_id,reviewer_id:user.employee_id,review_type:String(b.review_type||"annual").slice(0,50),scheduled_at:b.scheduled_at||null,status:b.status||"planned",summary:String(b.summary||"").slice(0,5000)||null,goals:Array.isArray(b.goals)?b.goals.slice(0,20):[]});await notify(b.employee_id,"review","Un entretien a été planifié",`Date prévue : ${b.scheduled_at||"à définir"}.`,"entretiens",r.data?.[0]?.id);await audit(user,"review_created","performance_review",r.data?.[0]?.id);return json({review:r.data?.[0]},201);
 }
 if(action==="review-update"&&req.method==="POST"){
  const b=await readBody(req),id=String(b.id||"").replace(/[^\w-]/g,""),review=(await db(qp("performance_reviews",{select:"id,employee_id,reviewer_id,status",id:`eq.${id}`,limit:"1"}))).data?.[0];if(!review||!await inScope(user,review.employee_id))return json({error:"Entretien indisponible."},404);const allowed=user.role==="admin"||user.role==="manager"&&review.reviewer_id===user.employee_id||user.role==="employee"&&review.employee_id===user.employee_id;if(!allowed||user.role==="employee"&&b.status==="completed")return json({error:"Vous ne pouvez pas modifier cet entretien."},403);const update:any={};if(["in_progress","completed"].includes(b.status))update.status=b.status;if(b.summary!==undefined)update.summary=String(b.summary).slice(0,5000);if(Array.isArray(b.goals))update.goals=b.goals.slice(0,20);if(update.status==="completed")update.validated_at=new Date().toISOString();await db(qp("performance_reviews",{id:`eq.${id}`}),"PATCH",update);await audit(user,"review_updated","performance_review",id,{status:update.status||review.status});return json({ok:true});
 }
 if(action==="tasks"&&req.method==="GET"){
  const ids=await visibleIDs(user);let filter:any={};if(user.role==="employee")filter={employee_id:`eq.${user.employee_id}`};if(user.role==="manager")filter={employee_id:`in.(${ids.join(",")})`};const rows=await namedRows("onboarding_tasks","id,employee_id,title,description,phase,assigned_to,due_date,status,completed_at,created_at",filter);const people=await employeesFor(user);return json({tasks:rows.map((r:any)=>({...r,...people.find((p:any)=>p.id===r.employee_id)}))});
 }
 if(action==="task-save"&&req.method==="POST"){
  const b=await readBody(req),employeeId=String(b.employee_id||"");if(user.role==="employee"||!await inScope(user,employeeId))return json({error:"Création de tâche hors de votre périmètre."},403);const title=String(b.title||"").trim();if(title.length<3)return json({error:"Le titre de la tâche est requis."},400);const assigned=String(b.assigned_to||"")||null;if(assigned&&!await inScope(user,assigned))return json({error:"La personne assignée est hors de votre périmètre."},403);const phase=["pre_arrival","arrival","departure"].includes(b.phase)?b.phase:"arrival",r=await db("onboarding_tasks","POST",{employee_id:employeeId,title:title.slice(0,160),description:String(b.description||"").slice(0,1000)||null,phase,assigned_to:assigned,due_date:b.due_date||null,created_by:user.employee_id});if(assigned)await notify(assigned,"task","Nouvelle tâche RH",title,"taches",r.data?.[0]?.id);await audit(user,"onboarding_task_created","onboarding_task",r.data?.[0]?.id);return json({task:r.data?.[0]},201);
 }
 if(action==="task-update"&&req.method==="POST"){
  const b=await readBody(req),id=String(b.id||"").replace(/[^\w-]/g,""),task=(await db(qp("onboarding_tasks",{select:"id,employee_id,assigned_to,status",id:`eq.${id}`,limit:"1"}))).data?.[0];if(!task||!await inScope(user,task.employee_id))return json({error:"Tâche indisponible."},404);if(user.role==="employee"&&task.assigned_to!==user.employee_id)return json({error:"Cette tâche ne vous est pas attribuée."},403);const status=["todo","in_progress","done","cancelled"].includes(b.status)?b.status:task.status;await db(qp("onboarding_tasks",{id:`eq.${id}`}),"PATCH",{status,completed_at:status==="done"?new Date().toISOString():null,updated_at:new Date().toISOString()});await audit(user,"onboarding_task_updated","onboarding_task",id,{status});return json({ok:true});
 }
 if(action==="notifications"&&req.method==="GET"){
  const notifications=await namedRows("noria_notifications","id,kind,title,body,target_page,target_id,read_at,created_at",{employee_id:`eq.${user.employee_id}`});return json({notifications,unread:notifications.filter((n:any)=>!n.read_at).length});
 }
 if(action==="notification-read"&&req.method==="POST"){
  const b=await readBody(req),id=String(b.id||"").replace(/[^\w-]/g,"");await db(qp("noria_notifications",{id:`eq.${id}`,employee_id:`eq.${user.employee_id}`}),"PATCH",{read_at:new Date().toISOString()});return json({ok:true});
 }
 if(action==="accounts"&&req.method==="GET"){
  if(!isHR(user))return json({error:"Accès réservé aux RH."},403);const accounts=await namedRows("hr_accounts","employee_id,identifier,role,enabled,must_change_password,last_login_at,created_at"),people=await db(qp("employees",{select:"id,first_name,last_name,staff_number,status",order:"last_name.asc",limit:"500"}));return json({accounts:accounts.map((a:any)=>({...a,...people.data?.find((p:any)=>p.id===a.employee_id)}))});
 }
 if(action==="account-update"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Accès réservé aux RH."},403);const b=await readBody(req),id=String(b.employee_id||"").replace(/[^\w-]/g,""),target=(await db(qp("hr_accounts",{select:"employee_id,role,enabled,session_version",employee_id:`eq.${id}`,limit:"1"}))).data?.[0];if(!target)return json({error:"Compte indisponible."},404);const {data:admins}=await db(qp("hr_accounts",{select:"employee_id",role:"eq.admin",enabled:"eq.true",limit:"100"}));const role=["admin","manager","employee"].includes(b.role)?b.role:target.role,enabled=b.enabled===undefined?target.enabled:b.enabled===true;if(target.role==="admin"&&(!enabled||role!=="admin")&&(admins||[]).length<=1)return json({error:"Le dernier compte administrateur actif ne peut pas être désactivé ou rétrogradé."},409);if(id===user.employee_id&&(!enabled||role!=="admin"))return json({error:"Vous ne pouvez pas désactiver ou rétrograder votre propre compte."},409);const patch:any={role,enabled};if(b.temporary_password){if(String(b.temporary_password).length<12)return json({error:"Le mot de passe provisoire doit compter au moins 12 caractères."},400);patch.password_hash=await hashPassword(String(b.temporary_password));patch.must_change_password=true}patch.session_version=Number(target.session_version||1)+1;await db(qp("hr_accounts",{employee_id:`eq.${id}`}),"PATCH",patch);await db(qp("employees",{id:`eq.${id}`}),"PATCH",{role});await audit(user,"account_updated","account",id,{role,enabled,reset_password:!!b.temporary_password});return json({ok:true});
 }
 if(action==="settings"&&req.method==="GET"){
  if(!isHR(user))return json({error:"Accès réservé aux RH."},403);const [settings,policies,holidays]=await Promise.all([db("noria_settings?select=setting_key,setting_value,updated_at&order=setting_key.asc"),namedRows("leave_policies","id,leave_type,counts_weekends,paid,requires_approval,enabled,annual_allowance,effective_from,updated_at"),namedRows("organization_holidays","id,holiday_date,label,location")]);return json({settings:settings.data||[],policies,holidays});
 }
 if(action==="settings-save"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Paramétrage réservé aux RH."},403);const b=await readBody(req),key=String(b.key||"");if(!["organization","retention"].includes(key))return json({error:"Paramètre inconnu."},400);let value:any={};if(key==="organization"){value={name:String(b.name||"").trim().slice(0,100),locations:Array.isArray(b.locations)?b.locations.map((x:any)=>String(x).trim().slice(0,100)).filter(Boolean).slice(0,50):[]};if(!value.name)return json({error:"Le nom de l’organisation est requis."},400)}else{for(const f of ["document_days","candidate_days"]){const n=b[f]===""||b[f]===undefined?null:Number(b[f]);if(n!==null&&(!Number.isFinite(n)||n<1||n>3650))return json({error:"Une durée de conservation doit être comprise entre 1 et 3650 jours."},400);value[f]=n}}const current=(await db(`noria_settings?select=setting_key&setting_key=eq.${key}&limit=1`)).data?.[0],row={setting_key:key,setting_value:value,updated_by:user.employee_id,updated_at:new Date().toISOString()};if(current)await db(`noria_settings?setting_key=eq.${key}`,"PATCH",row);else await db("noria_settings","POST",row);await audit(user,"settings_updated","setting",null,{key});return json({ok:true});
 }
 if(action==="leave-policy-save"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Paramétrage réservé aux RH."},403);const b=await readBody(req),leaveType=String(b.leave_type||"").trim().slice(0,80);if(leaveType.length<2)return json({error:"Le type d’absence est requis."},400);const current=(await db(qp("leave_policies",{select:"id",leave_type:`eq.${leaveType}`,limit:"1"}))).data?.[0],row={leave_type:leaveType,counts_weekends:b.counts_weekends===true,paid:b.paid===true,requires_approval:b.requires_approval!==false,enabled:b.enabled!==false,annual_allowance:b.annual_allowance===""||b.annual_allowance===undefined?null:Number(b.annual_allowance),updated_at:new Date().toISOString()};if(row.annual_allowance!==null&&(Number.isNaN(row.annual_allowance)||row.annual_allowance<0))return json({error:"Le droit annuel est invalide."},400);const result=current?await db(qp("leave_policies",{id:`eq.${current.id}`}),"PATCH",row):await db("leave_policies","POST",row);await audit(user,"leave_policy_updated","leave_policy",result.data?.[0]?.id,{leave_type:leaveType});return json({ok:true});
 }
 if(action==="holiday-save"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Paramétrage réservé aux RH."},403);const b=await readBody(req);if(!/^\d{4}-\d{2}-\d{2}$/.test(String(b.holiday_date||""))||String(b.label||"").trim().length<2)return json({error:"Date et libellé du jour férié requis."},400);const r=await db("organization_holidays","POST",{holiday_date:b.holiday_date,label:String(b.label).trim().slice(0,100),location:String(b.location||"").trim()||null});await audit(user,"holiday_created","organization_holiday",r.data?.[0]?.id);return json({ok:true},201);
 }
 if(action==="holiday-delete"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Paramétrage réservé aux RH."},403);const b=await readBody(req),id=String(b.id||"").replace(/[^\w-]/g,"");await db(qp("organization_holidays",{id:`eq.${id}`}),"DELETE");await audit(user,"holiday_deleted","organization_holiday",id);return json({ok:true});
 }
 if(action==="leave-balance-adjust"&&req.method==="POST"){
  if(!isHR(user))return json({error:"Action réservée aux RH."},403);const b=await readBody(req),id=String(b.employee_id||"").replace(/[^\w-]/g,""),delta=Number(b.delta_days);if(!Number.isFinite(delta)||delta===0||Math.abs(delta)>365)return json({error:"Saisissez un ajustement compris entre 0,01 et 365 jours."},400);const person=(await db(qp("employees",{select:"leave_balance",id:`eq.${id}`,limit:"1"}))).data?.[0],next=Number(person?.leave_balance||0)+delta;if(!person||next<0)return json({error:"Le solde ne peut pas devenir négatif."},409);await db(qp("employees",{id:`eq.${id}`}),"PATCH",{leave_balance:next});await db("leave_balance_transactions","POST",{employee_id:id,leave_type:String(b.leave_type||"Congés payés").slice(0,80),delta_days:delta,effective_date:b.effective_date||parisDate(),source_type:"manual_adjustment",source_id:crypto.randomUUID(),created_by:user.employee_id,note:String(b.note||"").slice(0,500)||null});await audit(user,"leave_balance_adjusted","employee",id,{delta_days:delta});return json({ok:true,leave_balance:next});
 }
 if(action==="audit"&&req.method==="GET"){
  if(!isHR(user))return json({error:"Accès réservé aux RH."},403);return json({events:await namedRows("noria_audit_log","id,actor_id,action,target_type,target_id,metadata,created_at")});
 }
 if(action==="export-record"&&req.method==="POST"){
  const b=await readBody(req),kind=String(b.kind||"");if(!["employees","leaves","attendance","recruitment","documents","reviews"].includes(kind))return json({error:"Export invalide."},400);if((kind==="recruitment"||kind==="employees")&&user.role==="employee")return json({error:"Export non autorisé."},403);await audit(user,"data_exported",kind,null,{row_count:Math.max(0,Math.min(Number(b.row_count)||0,500)),period:String(b.period||"").slice(0,100)});return json({ok:true});
 }
 if(action==="retention-review"&&req.method==="GET"){
  if(!isHR(user))return json({error:"Accès réservé aux RH."},403);const today=parisDate(),[docs,candidates]=await Promise.all([namedRows("employee_documents","id,employee_id,title,document_type,retention_until",{retention_until:`lte.${today}`}),namedRows("candidates","id,first_name,last_name,stage,retention_until",{retention_until:`lte.${today}`})]);return json({documents:docs,candidates});
 }
 return json({error:"Action inconnue."},404);
 }catch(error){const e=error as any;console.error("[noria-api]",e?.message||error);return json({error:e?.status&&e.status<500?e.message:"Le service est momentanément indisponible. Réessayez plus tard."},e?.status&&e.status<500?e.status:503)} };
Deno.serve(mainHandler);

