// Noria SIRH: protected API plus the browser application.
const PAGE = __PAGE__;
const STYLES = __STYLES__;
const APP = __APP__;
const PUBLIC_KEY = "sb_publishable_2eyDXjK_UK8mxZJdNp1bbw_jedfJBhQ";
const COOKIE = "noria_session";
const utf8 = new TextEncoder();
const b64url = (bytes: Uint8Array) => btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const unb64url = (s:string) => Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((s.length+3)%4)),c=>c.charCodeAt(0));
const safeEqual = (a:string,b:string) => {const x=utf8.encode(a),y=utf8.encode(b);if(x.length!==y.length)return false;let n=0;for(let i=0;i<x.length;i++)n|=x[i]^y[i];return n===0};
const json = (value:unknown,status=200,headers:Record<string,string>={}) => new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers}});
function serviceKey(){const direct=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(direct)return direct;try{return JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default}catch{return undefined}}
function config(){const url=Deno.env.get("SUPABASE_URL"),key=serviceKey();if(!url||!key)throw new Error("Le service RH est en cours de configuration.");return{url:url.replace(/\/$/,""),key}}
function sessionSecret(){const secret=Deno.env.get("SESSION_SECRET")||config().key;if(secret.length<32)throw new Error("La clé de session doit contenir au moins 32 caractères.");return secret}
async function db(path:string,method="GET",value?:unknown){const c=config(),headers:Record<string,string>={apikey:c.key,"Content-Type":"application/json",Prefer:method==="POST"?"return=representation":method==="PATCH"?"return=representation":"count=exact"};if(c.key.startsWith("eyJ"))headers.Authorization=`Bearer ${c.key}`;const r=await fetch(`${c.url}/rest/v1/${path}`,{method,headers,body:value===undefined?undefined:JSON.stringify(value),cache:"no-store"});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!r.ok)throw Object.assign(new Error(typeof data==="object"?(data.message||data.hint||"Erreur de base de données."):String(data)),{status:r.status});return{data,range:r.headers.get("content-range")}}
const qp=(table:string,p:Record<string,string>)=>`${table}?${new URLSearchParams(p)}`;
function cookie(req:Request){const v=(req.headers.get("cookie")||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(`${COOKIE}=`));return v?decodeURIComponent(v.slice(COOKIE.length+1)):""}
function cookieHeader(value:string,maxAge:number){return`${COOKIE}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function hmac(data:string){const key=await crypto.subtle.importKey("raw",utf8.encode(sessionSecret()),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64url(new Uint8Array(await crypto.subtle.sign("HMAC",key,utf8.encode(data))))}
async function makeToken(payload:Record<string,unknown>){const h=b64url(utf8.encode(JSON.stringify({alg:"HS256",typ:"JWT"}))),b=b64url(utf8.encode(JSON.stringify(payload))),raw=`${h}.${b}`;return`${raw}.${await hmac(raw)}`}
async function claims(req:Request){const p=cookie(req).split(".");if(p.length!==3)return null;const sig=await hmac(`${p[0]}.${p[1]}`);if(!safeEqual(sig,p[2]))return null;try{const c=JSON.parse(new TextDecoder().decode(unb64url(p[1])));return c.exp>Date.now()/1000?c:null}catch{return null}}
async function hashPassword(password:string,salt=crypto.getRandomValues(new Uint8Array(16)),iterations=310000){const key=await crypto.subtle.importKey("raw",utf8.encode(password),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return`pbkdf2$${iterations}$${b64url(salt)}$${b64url(new Uint8Array(bits))}`}
async function verifyPassword(password:string,stored:string){const [scheme,n,salt,digest]=stored.split("$");if(scheme!=="pbkdf2"||!n||!salt||!digest)return false;return safeEqual(await hashPassword(password,unb64url(salt),Number(n)),`pbkdf2$${n}$${salt}$${digest}`)}
async function current(req:Request){const c=await claims(req);if(!c?.sub)return null;const {data}=await db(qp("hr_accounts",{select:"employee_id,identifier,role,enabled,must_change_password,session_version",employee_id:`eq.${c.sub}`,limit:"1"})),a=data?.[0];if(!a?.enabled||(c.ver!==undefined&&Number(c.ver)!==Number(a.session_version)))return null;return{employee_id:a.employee_id,identifier:a.identifier,role:a.role,must_change_password:a.must_change_password===true,session_version:Number(a.session_version||1)}}
async function readBody(req:Request){const s=await req.text();if(s.length>7200000)throw Object.assign(new Error("Le fichier dépasse la taille autorisée."),{status:413});try{return JSON.parse(s||"{}") as any}catch{throw Object.assign(new Error("Requête invalide."),{status:400})}}
const employeeFields="id,staff_number,first_name,last_name,job_title,department,contract_type,start_date,end_date,location,phone_number,work_percentage,status,role,manager_id,leave_balance";
const isHR=(u:any)=>u.role==="admin";
const isManager=(u:any)=>u.role==="manager";
async function visibleIDs(u:any){if(u.role==="admin")return null;if(u.role==="employee")return[u.employee_id];const ids=new Set<string>([u.employee_id]),queue=[u.employee_id];while(queue.length&&ids.size<500){const parent=queue.shift()!,{data}=await db(qp("employees",{select:"id",manager_id:`eq.${parent}`,status:"neq.inactive",limit:"500"}));for(const child of data||[])if(!ids.has(child.id)){ids.add(child.id);queue.push(child.id);if(ids.size>=500)break}}return[...ids]}
async function inScope(u:any,id:string){if(u.role==="admin")return true;if(id===u.employee_id)return true;const ids=await visibleIDs(u);return ids?.includes(id)||false}
function idFilter(ids:string[]|null){return ids===null?{}:{employee_id:`in.(${ids.join(",")})`}}
function parisDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
function dateAfter(start:string,days:number){const d=new Date(`${start}T12:00:00`);d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function workdays(a:string,b:string,holidays:Set<string>=new Set(),weekends=false){let n=0;for(let d=new Date(`${a}T12:00:00`),end=new Date(`${b}T12:00:00`);d<=end;d.setDate(d.getDate()+1)){const iso=d.toISOString().slice(0,10);if((weekends||d.getDay()!==0&&d.getDay()!==6)&&!holidays.has(iso))n++}return n}
async function getDashboard(u:any){const ids=await visibleIDs(u),filters=idFilter(ids);const [{data:employees},{data:leaves},{data:jobs},{data:profile}]=await Promise.all([
 db(qp("employees",{select:employeeFields,status:"neq.inactive",order:"last_name.asc",limit:"500",...(ids?{id:`in.(${ids.join(",")})`}:{})})),
 db(qp("leave_requests",{select:"id,employee_id,leave_type,start_date,end_date,days,status,note,created_at,reviewed_at",order:"start_date.desc",limit:"500",...filters})),
 db(qp("job_postings",{select:"id,status",status:"eq.open",limit:"500"})),
 db(qp("employees",{select:"id,first_name,last_name,role,leave_balance",id:`eq.${u.employee_id}`,limit:"1"}))]);
 const today=parisDate(),mine=leaves.filter((x:any)=>x.employee_id===u.employee_id),approved=leaves.filter((x:any)=>x.status==="approved");return{summary:{employee_count:employees.length,on_leave_today:approved.filter((x:any)=>x.start_date<=today&&x.end_date>=today).length,pending_leave:leaves.filter((x:any)=>x.status==="pending").length,open_positions:jobs.length,leave_balance:profile?.[0]?.leave_balance??0,my_pending:mine.filter((x:any)=>x.status==="pending").length,my_approved:mine.filter((x:any)=>x.status==="approved").length,upcoming_leaves:approved.filter((x:any)=>x.start_date>=today).slice(0,5).map((l:any)=>({...l,...employees.find((e:any)=>e.id===l.employee_id)}))},employees:u.role==="employee"?[]:employees,leaves:leaves.map((l:any)=>({...l,...employees.find((e:any)=>e.id===l.employee_id)}))}}
async function namedRows(table:string,select:string,filters:Record<string,string>={}){return(await db(qp(table,{select,order:"created_at.desc",limit:"500",...filters}))).data||[]}
async function employeesFor(u:any){const ids=await visibleIDs(u),filter=ids===null?{}:{id:`in.(${ids.join(",")})`};return(await db(qp("employees",{select:"id,first_name,last_name,staff_number",status:"neq.inactive",order:"last_name.asc",limit:"500",...filter}))).data||[]}
async function audit(u:any,action:string,targetType:string,targetId:string|null=null,metadata:Record<string,unknown>={}){try{await db("noria_audit_log","POST",{actor_id:u.employee_id,action,target_type:targetType,target_id:targetId,metadata})}catch(error){console.error("[noria-audit]",String((error as any)?.message||error))}}
async function notify(employeeId:string,kind:string,title:string,body:string,targetPage:string,targetId:string|null=null){if(!employeeId)return;await db("noria_notifications","POST",{employee_id:employeeId,kind,title,body,target_page:targetPage,target_id:targetId})}
async function storage(path:string,method="GET",body?:BodyInit,headers:Record<string,string>={}){const c=config(),h:Record<string,string>={apikey:c.key,...headers};if(c.key.startsWith("eyJ"))h.Authorization=`Bearer ${c.key}`;const r=await fetch(`${c.url}/storage/v1/${path}`,{method,headers:h,body});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!r.ok)throw Object.assign(new Error(typeof data==="object"?(data.message||"Erreur de stockage."):String(data)),{status:r.status});return data}
async function signedDoc(path:string){const encoded=path.split("/").map(encodeURIComponent).join("/");const d=await storage(`object/sign/noria-documents/${encoded}`,"POST",JSON.stringify({expiresIn:90}),{"Content-Type":"application/json"});const c=config();return{url:d.signedURL?.startsWith("http")?d.signedURL:`${c.url}/storage/v1${d.signedURL}`}}
async function servePage(req:Request){const nonce=b64url(crypto.getRandomValues(new Uint8Array(18))),endpoint=new URL(req.url).pathname,script=`<script nonce="${nonce}">window.NORIA_CONFIG={endpoint:${JSON.stringify(endpoint)},apiKey:${JSON.stringify(PUBLIC_KEY)}};</script>`,html=PAGE.replace('<link rel="stylesheet" href="/styles.css">',`<style nonce="${nonce}">${STYLES}</style>`).replace('<script src="/app.js" defer></script>',`${script}<script nonce="${nonce}">${APP}</script>`);return new Response(html,{headers:{"content-type":"text/html; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","X-Robots-Tag":"noindex, nofollow, noarchive","Content-Security-Policy":`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'`}})}

__ROUTES__

